#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import sys
import argparse


class Brightness(object):
    file = "/sys/class/backlight/intel_backlight/brightness"

    def read_brightness(self):
        with open(self.file, 'r') as f:
            current_brightness = int(f.read())
        return current_brightness

    def write_brightness(self, nr):
        try:
            with open(self.file, 'w') as f:
                f.write(str(nr))
        except Exception as e:
            print(e)

    def increase_brightness(self, nr):
        self.write_brightness(self.read_brightness() + int(nr))

    def decrease_brightness(self, nr):
        self.write_brightness(self.read_brightness() - int(nr))


parser = argparse.ArgumentParser(description='Set laptop screen brightness.')
parser.add_argument('-i', '--increase',
                    metavar='number',
                    type=int,
                    help='Increase/decrease current brightness by chosen '
                         'number.')
parser.add_argument('-s', '--set',
                    metavar='number',
                    type=int,
                    help='Set brightness to your chosen number.')
parser.add_argument('-d', '--display',
                    action='store_true',
                    help='Show current brightness.')

args = parser.parse_args()

if len(sys.argv) == 1:
    parser.print_help()
    sys.exit(1)

if args.increase:
    chbright = Brightness()
    chbright.increase_brightness(args.increase)

if args.set:
    chbright = Brightness()
    chbright.write_brightness(args.set)

if args.display:
    chbright = Brightness()
    print('current brightness: {}'.format(chbright.read_brightness()))
