#!/usr/bin/env python

import sys
import argparse


class Brightness(object):
    file = "/sys/class/backlight/intel_backlight/brightness"
    #file = "brightness"

    def read_brightness(self):
        with open(self.file, 'r') as f:
            current_brightness = int(f.read())
        return current_brightness

    def write_brightness(self, nr):
        with open(self.file, 'w') as f:
            f.write(str(nr))

    def increase_brightness(self, nr):
        self.write_brightness(self.read_brightness() + int(nr))

    def decrease_brightness(self, nr):
        self.write_brightness(self.read_brightness() - int(nr))


parser = argparse.ArgumentParser(description='This is test', version='0.1')
#parser.parse_args()

#br = Brightness()
#br.write_brightness(sys.argv[1])
